export const environment = {
  production: true,
  auth: "auth",
  cache: "cache",
  fake: "fake",
  error: "error",
  profiler: "profiler",
  notify: "notify",
  header: "header",
  convert: "convert",
  loader: "loader",
  https: "https",
  base_api_url: "https://epico.gob.ec/ce_rest_des/servicio/",
  domain: "https://epico.gob.ec/",
  login: "/auth",
  usuario: "user",
  home: "/home",
  registro: "https://epico.gob.ec/ce_desarrollo/registro_emprendedor.php",
  pathActividad: '/paginas/servicios/programas/subprograma/etapa/'
};
